# Generated by Django 5.1.3 on 2024-11-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('session_token', models.CharField(max_length=50)),
            ],
        ),
    ]
