# Generated by Django 5.1.3 on 2024-11-19 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuposi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registration',
            new_name='Registrations',
        ),
    ]
