# Generated by Django 5.1.3 on 2024-11-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuposi', '0002_rename_registration_registrations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrations',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='registrations',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='registrations',
            name='session_token',
        ),
        migrations.RemoveField(
            model_name='registrations',
            name='username',
        ),
        migrations.AlterField(
            model_name='registrations',
            name='email',
            field=models.EmailField(default='email', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='password',
            field=models.CharField(default='password', max_length=255),
        ),
        migrations.AddField(
            model_name='registrations',
            name='firstName',
            field=models.CharField(default='firstname', max_length=100),
        ),
        migrations.AddField(
            model_name='registrations',
            name='lastName',
            field=models.CharField(default='lastname', max_length=100),
        ),
        migrations.AddField(
            model_name='registrations',
            name='userName',
            field=models.CharField(default='username', max_length=100, unique=True),
        ),
    ]
