# Generated by Django 5.1.3 on 2024-11-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuposi', '0003_remove_registrations_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='session_token',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
