# Generated by Django 5.1.3 on 2024-11-20 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuposi', '0005_giga_chat_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giga_chat_users',
            name='giga_photo',
        ),
    ]
